### ISSUE TITLE
Add sensors into Gazebo sim

### ISSUE THREAD

**Issue by peter2380123** [QUT-Motorsport/QUTMS_Autonomous#3]
Sensors include:

- [x] LiDAR
- [x]  GPS
- [x] IMU
- [x] Camera (stereo)

[AMZ](https://github.com/eufsa/eufs_sim#3-additional-sensors-) also has their additional sensor package, but might only be compatible with ros-kinetic. Try editing their codes or find an alternative of how to add sensors. 

[This Gazebo tutorial](http://gazebosim.org/tutorials?tut=ros_gzplugins) also lists all possible/built-in sensors.

**Comment by peter2380123** [comment]
PR #8 added LiDAR and a stereo camera.

**Comment by NickManjan** [comment]
Behaviour of LiDAR and Camera plugins must be investigated. Investigate use of spawn_model with a launch or world file

**Comment by NickManjan** [comment]
All sensors added to model with associated plugins
