### ISSUE TITLE
Extract data from simulation sensors

### ISSUE THREAD

**Issue by peter2380123** [QUT-Motorsport/QUTMS_Autonomous#9]
Depends on #3.
Once the sensors are added, we then need to extract information from it. 

For example, extract: 
- [] LiDAR data, and perhaps view it if the result is intuitive to understand. 
- [] GPS data, and outputs tracked positions using @NatoNine's script. 
- [] IMU and save it as csv for analysis.
- [] Camera data as image(s) and pass it to OpenCV for colour thresholding or feature extraction.

**Comment by NickManjan** [comment]
Using premade libgazebo_ros plugin libraries for now. Will add issue to investigate maybe writing our own
